#!/bin/bash
jq -r '
  .name as $name |
  .types[0].type.name as $type |
  (.weight / 10) as $formatted_weight |
  (.height / 10) as $formatted_height |
  "Pikachu is of type \($type), weighs \($formatted_weight)kg, and is \($formatted_height)m tall." '| \
awk -F',' '{printf "%s is of type %s, weighs %.1fkg, and is %.1fm tall.\n", $1, $2, $3/10, $4/10}' | \
sed 's/\([0-9]\)0kg/\1kg/; s/\([0-9]\)0m/\1m/'
